INSERT INTO tasks (user_id, title, description, due_date, completed, priority) VALUES
(1, 'Renew car insurance', 'Shop around for best rates and update coverage.', '2022-11-30', 1, 'Low'), 
(2, 'Write book review', 'Finish review for recently read book.', '2023-04-15', 0, 'Medium'), 
(3, 'Clean out gutters', 'Remove leaves and debris to prevent water damage.', '2025-09-15', 0, 'High'), 
(8, 'Visit dentist', 'Schedule checkup and cleaning.', '2024-03-12', 0, 'High'), 
(1, 'Learn a new language', 'Start basic lessons in French using an app.', '2023-10-31', 1, 'Low'), 
(2, 'Plan summer vacation', 'Research destinations and book accommodations.', '2024-07-20', 0, 'High'), 
(3, 'Update resume', 'Highlight recent skills and achievements.', '2024-05-15', 0, 'Medium'), 
(8, 'Buy birthday gift for friend', 'Find a unique and thoughtful present.', '2023-12-12', 1, 'High'), 
(3, 'Organize photos', 'Sort and categorize pictures from last trip.', '2024-04-25', 0, 'Low'), 
(1, 'Fix leaky faucet', 'Repair the dripping faucet in the bathroom sink.', '2022-12-20', 1, 'High'), 
(2, 'Volunteer at local shelter', 'Help out with various tasks.', '2024-06-25', 0, 'High'), 
(3, 'Start home improvement project', 'Begin painting the bedroom.', '2023-08-20', 0, 'Medium'), 
(8, 'Learn to cook a new dish', 'Master a signature recipe for pasta.', '2024-08-08', 0, 'High'), 
(1, 'Read classic novel', 'Start "Jane Eyre" and delve into the literary world.', '2023-03-05', 1, 'Low'), 
(2, 'Attend industry conference', 'Network with professionals and learn new trends.', '2024-09-12', 0, 'High'),
(3, 'Donate to charity', 'Support a cause close to your heart.', '2023-02-14', 1, 'Medium'),
(8, 'Go for a run', 'Start a regular running routine for fitness.', '2024-03-18', 0, 'High'), 
(1, 'Clean out garage', 'Sort through belongings and discard unnecessary items.', '2023-07-25', 0, 'Low');