INSERT INTO tasks (user_id, title, description, due_date, completed, priority) VALUES
(1, 'Renew car insurance', 'Shop around for best rates and update coverage.', '2023-11-30', 1, 'Low'), 
(1, 'Plan summer vacation', 'Research destinations and book accommodations.', '2024-07-20', 0, 'High'), 
(1, 'Create presentation slides', 'Design engaging and informative slides for meeting.', '2024-03-07', 0, 'Medium'), 
(1, 'Set budget for next month', 'Allocate funds for different categories.', '2024-03-01', 0, 'Low'), 
(1, 'Cook a healthy breakfast', 'Prepare a nutritious and delicious meal.', '2024-02-26', 0, 'Low'), 
(1, 'Read classic novel', 'Start "Moby Dick" and delve into the adventure.', '2024-02-05', 0, 'Medium'), 
(1, 'Clean out attic', 'Sort through belongings and discard unnecessary items.', '2024-01-25', 0, 'High'),
(2, 'Write book review', 'Finish up a review for recently read book.', '2023-04-15', 0, 'Medium'), 
(2, 'Update resume', 'Highlight recent skills and achievements.', '2024-03-15', 0, 'Medium'), 
(2, 'Schedule gym session', 'Book a time for a workout.', '2024-03-06', 0, 'Low'), 
(2, 'Research retirement options', 'Explore different investment options.', '2024-03-10', 0, 'High'), 
(2, 'Attend industry conference', 'Network with professionals and learn new trends.', '2024-04-12', 0, 'High'), 
(3, 'Clean out gutters', 'Remove leaves and debris to prevent water damage.', '2025-09-15', 0, 'High'), 
(3, 'Learn a new language', 'Start basic lessons in Spanish using an app.', '2023-10-31', 1, 'Low'), 
(3, 'Organize closet', 'Sort clothes, declutter items, and fold everything neatly.', '2024-03-16', 0, 'Medium'), 
(3, 'Meditate for 10 minutes', 'Reduce stress and improve focus with a short session.', '2024-02-22', 1, 'High'), 
(3, 'Pay off credit card debt', 'Make a payment towards eliminating debt.', '2024-02-28', 1, 'High'), 
(3, 'Start home improvement project', 'Begin painting the living room.', '2024-01-20', 0, 'Medium'),
(8, 'Visit dentist', 'Schedule checkup and cleaning.', '2024-03-12', 0, 'High'), 
(8, 'Buy birthday gift for friend', 'Find a unique and thoughtful present.', '2023-12-12', 1, 'High'), 
(8, 'Organize photos', 'Sort and categorize pictures from last trip.', '2024-04-25', 0, 'Low'), 
(8, 'Go for a run', 'Start a regular running routine for fitness.', '2024-03-18', 0, 'High'), 
(8, 'Balance checkbook', 'Reconcile bank statements and ensure accurate records.', '2024-03-05', 0, 'Low');